name: Deploy Node Application

on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}       
      - name: Build docker image
        run: docker build -t diockerhub/server .  
      - name: Publish image to docker hub
        run: docker push diockerhub/server:latest
        
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull diockerhub/server:latest
      - name: Delete old container
        run: sudo docker rm -f server-container || true
      - name: Run docker container
        run: sudo docker run -d -p 4000:4000 --name server-container -e MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} -e JWT_SECRET=tu_secreto -e PORT=4000 diockerhub/server
   